---
title: my write-ups!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: dbaser
author: dbaser
url: dbaser.github.io
description: ctfs, write-ups and hacking n' roll!
repository: dbaser/dbaser.github.io
permalink: "/:year/:month/:day/:title/"
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: compresseds
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
pigments: true
kramdown.syntax_highlighter_opts.block.line_numbers = true
gems:
- github-pages
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
whitelist:
- github-pages
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
