name: debugg.io
description: Debugging stories, coding, hacking and a little sarcasm.
author: mikengine
logo: /assets/img/fa-bug.png
image: /assets/img/fa-bug.png
repository: mikengine/mikengine.github.io

permalink: /:year/:month/:day/:title/

twitter:
  username: mikengine

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

sass:
  style: :compresseds
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

pigments: true

gems:
  - github-pages
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap

whitelist:
  - github-pages
  - jekyll-gist
  - jekyll-seo-tag
