name: //hardcoding
description: blog.hardcoding.io
location: Monterrey, Mx.

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

pigments: true

#gems
gems:
  - github-pages
  - jekyll-gist
whitelist:
  - jekyll-gist
  - github-pages
