name: debugg.io
description: Debugging stories, coding, hacking and a little sarcasm.
repository: mikengine/mikengine.github.io
twitter:
  username: mikengine
  image: /assets/fa-bug.png
author: mikengine
logo: /assets/fa-bug.png

permalink: /:year/:month/:day/:title/

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

sass:
  style: :compresseds
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

pigments: true

gems:
  - github-pages
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-github-metadata

whitelist:
  - github-pages
  - jekyll-gist
  - jekyll-seo-tag
